reloader:
  serviceAccount:
    create: true
    name: reloader
    annotations:
      # Convenção do ambiente: togglemaster-dev-reloader-irsa
      eks.amazonaws.com/role-arn: "arn:aws:iam::927738510198:role/togglemaster-dev-reloader-irsa"
  
  reloader:
    watchGlobally: true
    autoReloadAllDeployments: true
