external-secrets:
  serviceAccount:
    create: true
    name: external-secrets
    annotations:
      # Convenção do ambiente: togglemaster-dev-eso-irsa
      eks.amazonaws.com/role-arn: "arn:aws:iam::927738510198:role/togglemaster-dev-eso-irsa"
  
  installCRDs: true
  replicaCount: 1
