nginxGateway:
  serviceAccount:
    name: nginx-gateway
    annotations:
      # Convenção do ambiente: togglemaster-<env>-nginx-irsa
      eks.amazonaws.com/role-arn: "arn:aws:iam::927738510198:role/togglemaster-<env>-nginx-irsa"

  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

  service:
    annotations:
      app.kubernetes.io/managed-by: "nginx-gateway-fabric"
